FORMAT: 1A
HOST: http:

# Passpod :: 28/3/2018
Link for update:

See _META section

# Group ENVIRONMENTS

## Unnammed Endpoint [//]

### Passpod  PRODUCTION [POST]

+ Response 200



### Passpod  IO [POST]

+ Response 200



### Passpod  LOCAL [POST]

+ Response 200



### Passpod  COM [POST]

+ Response 200





# Group MODEMS FOR INVENTORY

## ExampleCom Modems D62d3e20 1b6b 11e8 942f C563d072a84c [//example.com/modems/d62d3e20-1b6b-11e8-942f-c563d072a84c]

### Delete one [DELETE]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Delete oneRequest)

    + Body

            {
                "name": "modem-1",
                "purchase_date": "2018-02-13T00:00:00Z",
                "supplier": "vodafone",
                "status": "broken",
                "purchase_price": "700.0000",
                "warehouse": "sing-tel-ware",
                "currency_code": "USD"
            }


+ Response 200



### Update one [PUT]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Update oneRequest)

    + Body

            {
                "name": "modem-1",
                "purchase_date": "2018-02-13T00:00:00Z",
                "supplier": "vodafone",
                "status": "broken",
                "purchase_price": "700.0000",
                "warehouse": "sing-tel-ware",
                "currency_code": "USD"
            }


+ Response 200



### Get one [GET]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Modems [//example.com/modems/]

### List All [GET]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200



### Create new [POST]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Create newRequest)

    + Body

            {
                "name": "modem-1",
                "purchase_date": "2018-02-13T00:00:00Z",
                "supplier": "vodafone",
                "status": "broken",
                "purchase_price": "700.0000",
                "warehouse": "sing-tel-ware",
                "currency_code": "USD"
            }


+ Response 200





# Group PRODUCT

## ExampleCom Products 37b25940 21c1 11e8 A25d Cda244878f03 [//example.com/products/37b25940-21c1-11e8-a25d-cda244878f03]

### Delete one [DELETE]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Delete oneRequest)

    + Body

            {
                "name": "modem-1",
                "purchase_date": "2018-02-13T00:00:00Z",
                "supplier": "vodafone",
                "status": "broken",
                "purchase_price": "700.0000",
                "warehouse": "sing-tel-ware",
                "currency_code": "USD"
            }


+ Response 200




## ExampleCom Products 2912edc0 2165 11e8 836b B937ae1d0dc3 [//example.com/products/2912edc0-2165-11e8-836b-b937ae1d0dc3]

### Update one Modem [PUT]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Update one ModemRequest)

    + Body

            {
                "title": "Modem One",
                "description": "Vodafone modem available to rent.",
                "price": 100,
                "currency_code": "USD",
                "image_file": "image-data.jpg",
                "product_type": "modem",
                "status": "active",
                "details": {
                    "country_id": "10a34500-5b55-53f8-baae-6f7f038eaa56"
                }
            }


+ Response 200




## ExampleCom Products 67136c70 227e 11e8 B133 0367a6497679 [//example.com/products/67136c70-227e-11e8-b133-0367a6497679]

### Get one [GET]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Files [//example.com/files/]

### Upload product image file [POST]
+ Attributes
    + files (string, required)

    + type (string, required)

        + Sample: product
    + product_type (string, required)

        + Sample: modem

+ Request (application/x-www-form-urlencoded)
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Products [//example.com/products/{?currency_code}]

### List All [GET]
+ Parameters
    + currency_code (string, required)

        + Sample: SGD

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Products [//example.com/products/{?type}]

### List All Modem [GET]
+ Parameters
    + type (string, required)

        + Sample: modem

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Products [//example.com/products/]

### Create new Modem [POST]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Create new ModemRequest)

    + Body

            {
                "title": "Sample Modem One",
                "description": "Vodafone modem available to rent.",
                "price": 100,
                "currency_code": "USD",
                "image_file": "image-data.jpg",
                "product_type": "modem",
                "status": "active",
                "details": {
                    "country_id": "10a34500-5b55-53f8-baae-6f7f038eaa56"
                }
            }


+ Response 200





# Group VOUCHERS

## ExampleCom Bookings 8a4970bf B9dd 448b 8c24 59dadb5c3766 Vouchers Bd3384b5 F51f 49d8 8811 B8b3d5c5f003 [//example.com/bookings/8a4970bf-b9dd-448b-8c24-59dadb5c3766/vouchers/bd3384b5-f51f-49d8-8811-b8b3d5c5f003]

### Download Voucher [GET]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Bookings 8a4970bf B9dd 448b 8c24 59dadb5c3766 Vouchers [//example.com/bookings/8a4970bf-b9dd-448b-8c24-59dadb5c3766/vouchers/]

### Get Available Vouchers for a Booking [GET]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200





# Group WISHLIST

## ExampleCom Users Wishlists [//example.com/users/wishlists]

### Add Attraction to Wishlist [POST]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Add Attraction to WishlistRequest)

    + Body

            {
                "attractionUUID": "642cf2e0-f2bf-5120-a496-6383be750b62"
            }


+ Response 200




## ExampleCom Users Wishlists [//example.com/users/wishlists{?language_code,currency_code}]

### Get Current User Wishlist [GET]
+ Parameters
    + language_code (string, required)

        + Sample: ID
    + currency_code (string, required)

        + Sample: IDR

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Users Wishlists 642cf2e0 F2bf 5120 A496 6383be750b62 [//example.com/users/wishlists/642cf2e0-f2bf-5120-a496-6383be750b62]

### Remove Attraction from Wishlist [DELETE]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200





# Group ATTRACTION

## ExampleCom Attractions Destinations 5a5682b8 C8d6 5f15 97ef De4c66ea5695 Types D3c54653 Dd05 598f B193 F6683d1064ab [//example.com/attractions/destinations/5a5682b8-c8d6-5f15-97ef-de4c66ea5695/types/d3c54653-dd05-598f-b193-f6683d1064ab{?page,limit,language_code,order,date}]

### List by Type [GET]
+ Parameters
    + page (number, required)

        + Sample: 1
    + limit (number, required)

        + Sample: 10
    + language_code (string, required)

        + Sample: ID
    + order (string, required)

        + Sample: title
    + date (string, required)

        + Sample: 2018-03-08

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Attractions Destinations 5a5682b8 C8d6 5f15 97ef De4c66ea5695 [//example.com/attractions/destinations/5a5682b8-c8d6-5f15-97ef-de4c66ea5695{?page,limit,language_code,currency_code,order,date}]

### List by Destination [GET]
+ Parameters
    + page (number, required)

        + Sample: 1
    + limit (number, required)

        + Sample: 10
    + language_code (string, required)

        + Sample: ID
    + currency_code (string, required)

        + Sample: IDR
    + order (string, required)

        + Sample: base_price,title
    + date (string, required)

        + Sample: 2018-04-25

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Attractions Recently Views [//example.com/attractions/recently-views]

### Recently Views [GET]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Attractions Types [//example.com/attractions/types]

### List Attraction Type [GET]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Attractions 2e784242 Ce57 55d2 97cd Eb5e4bb08a32 [//example.com/attractions/2e784242-ce57-55d2-97cd-eb5e4bb08a32{?language_code,currency_code,date}]

### Detail [GET]
+ Parameters
    + language_code (string, required)

        + Sample: ID
    + currency_code (string, required)

        + Sample: IDR
    + date (string, required)

        + Sample: 2018-03-21

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200





# Group BOOKINGS

## ExampleCom Hooks Bookings Voucher Ready [//example.com/hooks/bookings/voucher-ready]

### Voucher Ready [POST]

+ Request (application/json)
    + Attributes (Voucher ReadyRequest)


+ Response 200





# Group MAINTENANCESTATUS

## ExampleCom Maintenance Status [//example.com/maintenance-status/]

### Set maintenance status [PUT]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Set maintenance statusRequest)

    + Body

            {
                "value": true
            }


+ Response 200




## ExampleCom Maintenance Status [//example.com/maintenance-status]

### Maintenance status [GET]

+ Response 200





# Group Claimers

## ExampleCom Coupons 262c2580 1775 11e8 9284 07fb71fb3431 Claimers [//example.com/coupons/262c2580-1775-11e8-9284-07fb71fb3431/claimers/]

### ClaimersDelete coupons claimer relationship with user [DELETE]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (ClaimersDelete coupons claimer relationship with userRequest)

    + Body

            {
                "userUUID": "6d730960-1133-11e8-b815-ef31569eb8a0"
            }


+ Response 200



### ClaimersCreate coupons claimer relationship with user [POST]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (ClaimersCreate coupons claimer relationship with userRequest)

    + Body

            {
                "userUUID": "6d730960-1133-11e8-b815-ef31569eb8a0"
            }


+ Response 200



### ClaimersGet coupons claimers [GET]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200





# Group EXCHANGERATE

## ExampleCom Exchange Rates 7456b6a0 16e2 11e8 92cb 13a5479f8763 [//example.com/exchange-rates/7456b6a0-16e2-11e8-92cb-13a5479f8763]

### View single exchangerates [GET]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Exchange Rates [//example.com/exchange-rates]

### View all exchange rates [GET]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Exchange Rates 9e486bc0 1840 11e8 Be28 4533b8f2d941 [//example.com/exchange-rates/9e486bc0-1840-11e8-be28-4533b8f2d941]

### Update single exchangerates [PUT]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (object)

    + Body

            {}


+ Response 200





# Group ORDER

## ExampleCom Carts [//example.com/carts]

### Add to Cart Modem [POST]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Add to Cart ModemRequest)

    + Body

            {
                "productable_id": "",
                "productable_type": "product",
                "order_detail": {
                    "qty": 1
                }
            }


+ Response 200



### Add to Cart Attraction [POST]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Add to Cart AttractionRequest)

    + Body

            {
                "productable_id": "d5a03ea2-e06e-5d01-84b7-94530b1059f7",
                "productable_type": "attraction",
                "order_detail": {
                    "attraction_package_id": "efedb1fc-f150-5eaa-bf6e-fc202f6114bd",
                    "date": "2018-03-16",
                    "adults": 1,
                    "children": 0,
                    "seniors": 0,
                    "time_slot_id": null
                }
            }


+ Response 200



### View Cart for Current User [GET]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Orders 1ab66de0 26cb 11e8 Af7d 2372a60c73e0 Token [//example.com/orders/1ab66de0-26cb-11e8-af7d-2372a60c73e0/token]

### Generate Nicepay Token for Current User [POST]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Checkout [//example.com/checkout]

### Checkout for Current User [POST]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Checkout for Current UserRequest)

    + Body

            {
                "salutation": "Mr.",
                "first_name": "Satrio",
                "last_name": "Wisnugroho",
                "email": "wisnugrohosatrio@gmail.com",
                "phone_number": "+6282138844644"
            }


+ Response 200




## ExampleCom Carts 27b17f90 2724 11e8 9886 75e9e15e90a8 [//example.com/carts/27b17f90-2724-11e8-9886-75e9e15e90a8]

### Empty Cart for Current User [DELETE]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Orders Dd4c3890 281e 11e8 A629 273a4506f2a0 [//example.com/orders/dd4c3890-281e-11e8-a629-273a4506f2a0]

### See Detail Order [GET]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Orders 1ab66de0 26cb 11e8 Af7d 2372a60c73e0 Banks [//example.com/orders/1ab66de0-26cb-11e8-af7d-2372a60c73e0/banks]

### Bank Transfer for Current User [PUT]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Orders 1ab66de0 26cb 11e8 Af7d 2372a60c73e0 Confirm [//example.com/orders/1ab66de0-26cb-11e8-af7d-2372a60c73e0/confirm]

### Confirm Booking for Current User [PUT]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Bookings [//example.com/bookings]

### Bookings for Current User [GET]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200





# Group DESTINATION

## ExampleCom Destinations 5a5682b8 C8d6 5f15 97ef De4c66ea5695 Attractions 0a44057a 78af 5fd1 A6b0 3cf9ce03d0c1 [//example.com/destinations/5a5682b8-c8d6-5f15-97ef-de4c66ea5695/attractions/0a44057a-78af-5fd1-a6b0-3cf9ce03d0c1]

### Remove Attraction from Destination [DELETE]
+ Attributes
    + images (string, required)


+ Request (application/x-www-form-urlencoded)
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Destinations Ae98e040 15f7 11e8 Aa79 83b62653d13c [//example.com/destinations/ae98e040-15f7-11e8-aa79-83b62653d13c]

### Get Single Destination [GET]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200



### Delete Destination [DELETE]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Destinations [//example.com/destinations]

### Get All Destinations [GET]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200



### Create Destination [POST]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Create DestinationRequest)

    + Body

            {
                "name": "Java",
                "image_file": {
                    "wide": "singapore-wide.jpg",
                    "narrow": "singapore-narrow.jpg"
                },
                "experience_count": 0,
                "priority": 1
            }


+ Response 200




## ExampleCom Destinations 5a5682b8 C8d6 5f15 97ef De4c66ea5695 Attractions D5a03ea2 E06e 5d01 84b7 94530b1059f7 [//example.com/destinations/5a5682b8-c8d6-5f15-97ef-de4c66ea5695/attractions/d5a03ea2-e06e-5d01-84b7-94530b1059f7]

### Add Attraction to Destination [POST]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Destinations 5a5682b8 C8d6 5f15 97ef De4c66ea5695 [//example.com/destinations/5a5682b8-c8d6-5f15-97ef-de4c66ea5695]

### Update Destination [PUT]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Update DestinationRequest)

    + Body

            {
                "priority": 100
            }


+ Response 200




## ExampleCom Files [//example.com/files/]

### Upload Destination Image File [POST]
+ Attributes
    + files (string, required)

    + type (string, required)

        + Sample: destination-image
    + width-option (string, required)

        + Sample: wide

+ Request (application/x-www-form-urlencoded)
    + Headers

            Authorization:{{authorization}}




+ Response 200





# Group COUPON

## ExampleCom Coupons 03072b40 1518 11e8 A4d9 374eb03e380b [//example.com/coupons/03072b40-1518-11e8-a4d9-374eb03e380b]

### Delete coupon [DELETE]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Coupons 262c2580 1775 11e8 9284 07fb71fb3431 [//example.com/coupons/262c2580-1775-11e8-9284-07fb71fb3431]

### Update coupon [PUT]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Update couponRequest)

    + Body

            {
                "id": "262c2580-1775-11e8-9284-07fb71fb3431",
                "code": "YEYEAH",
                "title": "Discount akhir tahun lagi!",
                "status": "unavailable",
                "image_file": "sample-image.jpg",
                "max_usage": "10",
                "max_usage_per_user": "2",
                "platform": "all",
                "first_order_only": false,
                "first_user_only": false,
                "product_type": "all",
                "discount_type": "PERCENTAGE_CUT",
                "discount_amount": "0",
                "start_at": "2018-03-08T09:57:32Z",
                "end_at": "2018-04-08T09:57:32Z",
                "description": "Something is happening! Take cover!",
                "min_amount": 500000,
                "country_code": null
            }


+ Response 200



### Get one coupon [GET]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Coupons [//example.com/coupons]

### Get All [GET]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200



### Create new coupon [POST]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Create new couponRequest)

    + Body

            {
                "title": "Diskon akhir tahun",
                "code": "BANGBANG",
                "status": "available",
                "max_usage": "1",
                "max_usage_per_user": "1",
                "image_file": "sample-image.jpg",
                "discount_type": "PRICE_CUT",
                "discount_amount": "200000",
                "start_at": "2018-02-18T00:00:00Z",
                "end_at": "2018-02-21T00:00:00Z",
                "description": null,
                "min_amount": 0
            }


+ Response 200



+ Response 400

        Bad Request



    + Body

            {"code":400,"status":false,"message":"Bad Request","meta":{},"data":[{"title.presence":{"en":"Title can't be blank","id":"Title can't be blank"}}]}



## ExampleCom Files [//example.com/files/]

### Upload coupon image file [POST]
+ Attributes
    + files (string, required)

    + type (string, required)

        + Sample: coupon-image

+ Request (application/x-www-form-urlencoded)
    + Headers

            Authorization:{{authorization}}




+ Response 200





# Group AUTH

## ExampleCom Auth Login [//example.com/auth/login]

### Local Login  Admin [POST]

+ Request (application/json)
    + Attributes (Local Login  AdminRequest)

    + Body

            {
                "email": "admin@passpod.id",
                "password": "password"
            }


+ Response 200



### Local Login  Normal User [POST]

+ Request (application/json)
    + Attributes (Local Login  Normal UserRequest)

    + Body

            {
                "email": "wisnugrohosatrio@gmail.com",
                "password": "password"
            }


+ Response 200




## ExampleCom Auth Register [//example.com/auth/register]

### Register [POST]

+ Request (application/json)
    + Attributes (RegisterRequest)

    + Body

            {
                "first_name": "Skyshi",
                "last_name": "Tampomas",
                "email": "developer@skyshi.com",
                "password": "12345678"
            }


+ Response 200




## ExampleCom Auth Reset Password [//example.com/auth/reset-password]

### Reset Password [POST]

+ Request (application/json)
    + Attributes (Reset PasswordRequest)

    + Body

            {
                "token": "U2FsdGVkX1/KszvvNLReh6J89uW7WSC6qzjn5m7lINSnN8lwGeaa9yGL2VEi4HX+/jeb1zNtvjLRJvxt4twiXQ==",
                "new_password": "12345678"
            }


+ Response 200




## ExampleCom Auth Reset [//example.com/auth/reset]

### Forgot Password [POST]

+ Request (application/json)
    + Attributes (Forgot PasswordRequest)

    + Body

            {
                "email": "wisnugrohosatrio@gmail.com"
            }


+ Response 200





# Group SUBDISTRICT

## ExampleCom Addresses Sub Districts [//example.com/addresses/sub-districts/{?district_id}]

### Get all subdistricts of districts copy [GET]
+ Parameters
    + district_id (string, required)

        + Sample: 219ec720-29ea-11e8-b372-95fc5199ca18

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Addresses Sub Districts [//example.com/addresses/sub-districts/]

### Get all subdistricts [GET]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Addresses Sub Districts 51cbf9f0 2b15 11e8 85a5 9d1b727ad583 [//example.com/addresses/sub-districts/51cbf9f0-2b15-11e8-85a5-9d1b727ad583]

### Get one sub district [GET]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200





# Group SAVED COUPON

## ExampleCom Users Saved Coupons [//example.com/users/saved_coupons/]

### Add Attraction to Current User Wishlist [POST]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Add Attraction to Current User WishlistRequest)

    + Body

            {
                "couponUUID": "262c2580-1775-11e8-9284-07fb71fb3431"
            }


+ Response 200




## ExampleCom Users Saved Coupons 262c2580 1775 11e8 9284 07fb71fb3431 [//example.com/users/saved_coupons/262c2580-1775-11e8-9284-07fb71fb3431]

### Remove Attraction from Current User Wishlist [DELETE]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Remove Attraction from Current User WishlistRequest)

    + Body

            {
                "couponUUID": "262c2580-1775-11e8-9284-07fb71fb3431"
            }


+ Response 200




## ExampleCom Users Saved Coupons [//example.com/users/saved_coupons]

### Get Current User Wishlist [GET]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200





# Group ACTIVATION VERIFICATION  OTP

## ExampleCom Auth Resend Activation Mail [//example.com/auth/resend-activation-mail]

### Resend Activation mail [POST]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Resend Activation mailRequest)

    + Body

            {
                "email": "wisnugrohosatrio@gmail.com"
            }


+ Response 200




## ExampleCom Users Phone [//example.com/users/phone]

### Request Phone Number Ownership Verification Send OTP [POST]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Request Phone Number Ownership Verification Send OTPRequest)

    + Body

            {
                "phone_number": "+628231231233"
            }


+ Response 200




## ExampleCom Users Phone Verify Update [//example.com/users/phone/verify-update]

### Verify Phone Number Change [POST]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Verify Phone Number ChangeRequest)

    + Body

            {
                "code": "82233332593"
            }


+ Response 200




## ExampleCom Auth Verify [//example.com/auth/verify{?token}]

### Activate Account [GET]
+ Parameters
    + token (string, required)

        + Sample: U2FsdGVkX1+PvbfttWFkxVdMPJthZTIC8ECBW2P3JpEw9BOfc9H/P3vcZekSuPMq

+ Request (application/json)



+ Response 200




## ExampleCom Users Phone Verify [//example.com/users/phone/verify]

### Verify Phone Number Ownership [POST]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Verify Phone Number OwnershipRequest)

    + Body

            {
                "code": "568124"
            }


+ Response 200




## ExampleCom Users Phone [//example.com/users/phone/]

### Request Phone Number Change [POST]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Request Phone Number ChangeRequest)

    + Body

            {
                "phone_number": "+6282233332593"
            }


+ Response 200





# Group COLLECTIONS

## F0f97c3c99c0df5f6019 [/f0f97c3c99c0df5f6019]

### API collection Update Link Avre [GET]
previous:

https://www.getpostman.com/collections/f0f97c3c99c0df5f6019

+ Response 200




## A9edc1bdcb7b6a27ad9a [/a9edc1bdcb7b6a27ad9a]

### API collection Latest JointThis [GET]

+ Response 200




## Df9eed9bb62932b51692 [/df9eed9bb62932b51692]

### API collection Update Link Wisnu [GET]

+ Response 200





# Group Eligible Users

## ExampleCom Coupons 262c2580 1775 11e8 9284 07fb71fb3431 Claimers [//example.com/coupons/262c2580-1775-11e8-9284-07fb71fb3431/claimers/]

### Eligible UsersDelete coupons eligibleusers relation with user [DELETE]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Eligible UsersDelete coupons eligibleusers relation with userRequest)

    + Body

            {
                "userUUID": "6d730960-1133-11e8-b815-ef31569eb8a0"
            }


+ Response 200




## ExampleCom Coupons 262c2580 1775 11e8 9284 07fb71fb3431 Eligible Users [//example.com/coupons/262c2580-1775-11e8-9284-07fb71fb3431/eligible_users/]

### Eligible UsersGet coupons eligibleusers [GET]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200



### Eligible UsersCreate coupons eligibleusers relation with user [POST]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Eligible UsersCreate coupons eligibleusers relation with userRequest)

    + Body

            {
                "userUUID": "6d730960-1133-11e8-b815-ef31569eb8a0"
            }


+ Response 200





# Group BANNER

## ExampleCom Banners 7456b6a0 16e2 11e8 92cb 13a5479f8763 [//example.com/banners/7456b6a0-16e2-11e8-92cb-13a5479f8763]

### Delete single banner [DELETE]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200



### Update single banner [PUT]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Update single bannerRequest)

    + Body

            {
                "title": "Banner Ones",
                "priority": 3,
                "image_file": {
                    "mobile": "9bd88ed0-2365-11e8-aedc-2d60910e9b56-mobile.jpg",
                    "original": "9bd88ed0-2365-11e8-aedc-2d60910e9b56-original.jpg"
                }
            }


+ Response 200




## ExampleCom Banners 43fdba00 1de8 11e8 Aa29 09de6febcf21 [//example.com/banners/43fdba00-1de8-11e8-aa29-09de6febcf21]

### View single banner [GET]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Banners [//example.com/banners]

### Register new banner [POST]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Register new bannerRequest)

    + Body

            {
                "title": "Banner One",
                "priority": 3,
                "image_file": {
                    "mobile": "f75f9f10-1de7-11e8-aa29-09de6febcf21-mobile.png",
                    "original": "f75f9f10-1de7-11e8-aa29-09de6febcf21-original.png"
                }
            }


+ Response 200



### View all banners [GET]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Files [//example.com/files/]

### Upload banner file [POST]
+ Attributes
    + files (string, required)

    + type (string, required)

        + Sample: banner

+ Request (application/x-www-form-urlencoded)
    + Headers

            Authorization:{{authorization}}




+ Response 200





# Group I18N

## ExampleCom I18n Spreadsheet [//example.com/i18n/spreadsheet]

### Upload new spreadsheet [POST]
+ Attributes
    + file (string, required)


+ Request (application/x-www-form-urlencoded)
    + Headers

            Authorization:{{authorization}}




+ Response 200





# Group USER

## ExampleCom Users Me [//example.com/users/me]

### View Currently Logged User [GET]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200



### Get Currently Logged User Profile [GET]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Users [//example.com/users]

### Update User [PUT]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Update UserRequest)

    + Body

            {
                "first_name": "Satrio",
                "last_name": "Wisnugroho",
                "country_code": "ID",
                "language_code": "ID",
                "currency_code": "IDR",
                "old_password": "password",
                "password": "12345678",
                "profile_picture": "profile_693e9af84d10c16df38c1e27e1dbb7_0.png"
            }


+ Response 200




## ExampleCom Files [//example.com/files/]

### Upload Profile Picture [POST]
+ Attributes
    + files (string, required)

    + type (string, required)

        + Sample: profile-picture

+ Request (application/x-www-form-urlencoded)
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Users [//example.com/users{?page,limit}]

### List Users [GET]
+ Parameters
    + page (number, required)

        + Sample: 1
    + limit (number, required)

        + Sample: 10

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Users 6d730960 1133 11e8 B815 Ef31569eb8a0 [//example.com/users/6d730960-1133-11e8-b815-ef31569eb8a0]

### View Single User [GET]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200





# Group MARKUP PRICE

## ExampleCom Markup Prices 3c7eabb0 16bb 11e8 A6bb 7fa88db32eaf [//example.com/markup_prices/3c7eabb0-16bb-11e8-a6bb-7fa88db32eaf]

### Delete one markup prices [DELETE]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Markup Prices 8c6a1250 16ba 11e8 A226 09f99edc5548 [//example.com/markup_prices/8c6a1250-16ba-11e8-a226-09f99edc5548]

### Update one markup prices [PUT]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Update one markup pricesRequest)

    + Body

            {
                "attraction_id": "6d730960-1133-11e8-b815-ef31569eb8a0",
                "markup_value": "1200"
            }


+ Response 200




## ExampleCom Markup Prices [//example.com/markup_prices/]

### Create new markup prices [POST]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Create new markup pricesRequest)

    + Body

            {
                "attraction_id": "6d730960-1133-11e8-b815-ef31569eb8a0",
                "markup_value": "120"
            }


+ Response 200




## ExampleCom Markup Prices 6d730960 1133 11e8 B815 Ef31569eb8a0 [//example.com/markup_prices/6d730960-1133-11e8-b815-ef31569eb8a0]

### Get one markup prices [GET]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Markup Prices [//example.com/markup_prices]

### Get all markup prices [GET]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200





# Group DISTRICT

## ExampleCom Addresses Districts [//example.com/addresses/districts/{?city_id}]

### Get all districts of city [GET]
+ Parameters
    + city_id (string, required)

        + Sample: 54738a10-29f3-11e8-afc3-138c9e03a70e

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Addresses Districts 51cae880 2b15 11e8 85a5 9d1b727ad583 [//example.com/addresses/districts/51cae880-2b15-11e8-85a5-9d1b727ad583]

### Get one district [GET]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Addresses Districts [//example.com/addresses/districts/]

### Get all districts [GET]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200





# Group AUTH NOTIFICATION SUBSCRIBING

## ExampleCom Auth Login Social [//example.com/auth/login/social]

### Social Login [POST]

+ Request (application/json)
    + Attributes (Social LoginRequest)

    + Body

            {
                "provider_type": "facebook",
                "provider_id": "10209485407847211",
                "provider_token": "EAAQiGg8LuYMBAC4TDm4VeZC2iEP9qiCxDZBivg89baV8kFjvxhPwOoWHvVroZCz1XsiPGeS8o0DeKIgZBJnIB6aDH29XXebffuoZAD8NjRNEN34E7dfhaDtKZAS7Cq4N2fBtK8OJzuYuqruiw0QYOfqCA20a4dRBAZD",
                "notification_key": "fhh33XfKLe4:APA91bEXCK09U4j2t33r7EE1-kMm0ryx4YR0bVsNguAePGruhsO5nCODvAiHYcVNunW-3UnJzvjhugFXDEvSQ1ECCiHnXFNLZ9xAyythGgboS0Lg9Xz7LJ8154WtvYUoS_kQ7zV7lxqE"
            }


+ Response 200




## ExampleCom Auth Login [//example.com/auth/login]

### Local Login [POST]

+ Request (application/json)
    + Attributes (Local LoginRequest)

    + Body

            {
                "email": "wisnugrohosatrio@gmail.com",
                "password": "password",
                "notification_key": "dT4k4zE5ae8:APA91bFkNI42O-UhYk9I27npk24Mt80ltiSEE_7msarN8NMbzGEAg52vMkl8v6Z0m2_bnkXZsL4hDrdjsVbye2RWc0u_xy_uqHfONM4zkyBtsqvub4lqY1QrjBsk99xUEdnejU8NAkv7"
            }


+ Response 200




## ExampleCom Auth Register [//example.com/auth/register]

### Register [POST]

+ Request (application/json)
    + Attributes (RegisterRequest54)

    + Body

            {
                "first_name": "Skyshi",
                "last_name": "Tampomas",
                "email": "developessr@skyshi.com",
                "password": "12345678",
                "notification_key": "dF_3FA64NAg:APA91bFkli43f9zA7JAOJt9rzRGIdzLUncUWkTlTP944us2z6_A4s1PbUlozj_lXfzeEg340LxNxbYKu1cCDVjPZIsk5jV8H8e4uyft6ElzZB-jTv4aLQu0jRxmPugZCqSLXFPBrNke-"
            }


+ Response 200





# Group NOTIFICATIONS

## ExampleCom Users Notifications [//example.com/users/notifications/]

### Get Current User Notification List [GET]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200





# Group PROVINCE

## ExampleCom Addresses Provinces [//example.com/addresses/provinces]

### Get all provinces [GET]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Addresses Provinces 2b85d9a0 2b15 11e8 85a5 9d1b727ad583 [//example.com/addresses/provinces/2b85d9a0-2b15-11e8-85a5-9d1b727ad583]

### Get one province [GET]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200





# Group PRESET

## ExampleCom Presets About [//example.com/presets/about{?language}]

### Get about preset [GET]
+ Parameters
    + language (string, required)

        + Sample: id

+ Response 200




## ExampleCom Presets Languages [//example.com/presets/languages]

### Get language list preset [GET]

+ Response 200




## ExampleCom Presets Countries [//example.com/presets/countries]

### Get currency preset [GET]

+ Response 200




## ExampleCom Presets Currencies [//example.com/presets/currencies]

### Get country list preset [GET]

+ Response 200





# Group POPULAR ATTRACTIONS

## ExampleCom Attractions Populars 258c4d9a 1ac6 11e8 8572 100ba914aaac [//example.com/attractions/populars/258c4d9a-1ac6-11e8-8572-100ba914aaac]

### Delete popular attraction [DELETE]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200



### Update popular attraction [PUT]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Update popular attractionRequest)

    + Body

            {
                "attraction_id": "258c5832-1ac6-11e8-8572-100ba914aaac",
                "origin": "eng",
                "priority": 1
            }


+ Response 200




## ExampleCom Attractions Populars Origin Id [//example.com/attractions/populars/origin/id]

### List All [GET]

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Attractions Populars [//example.com/attractions/populars/]

### Add popular attraction [POST]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}

    + Attributes (Add popular attractionRequest)

    + Body

            {
                "attraction_id": "d5a03ea2-e06e-5d01-84b7-94530b1059f7",
                "modifier_type": "origin",
                "modifier_value": "id",
                "priority": 1
            }


+ Response 200




## ExampleCom Attractions Populars [//example.com/attractions/populars/{?by,of}]

### List All using query [GET]
+ Parameters
    + by (string, required)

        + Sample: origin
    + of (string, required)

        + Sample: id

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200





# Group PAYMENT

## ExampleCom Hooks Payments Notification [//example.com/hooks/payments/notification]

### Payment Notification [POST]

+ Request (application/json)
    + Attributes (string)

    + Body

            []


+ Response 200




## ExampleCom Hooks Bookings Status Changed [//example.com/hooks/bookings/status-changed]

### Booking Status Changed [POST]

+ Request (application/json)
    + Attributes (Booking Status ChangedRequest)


+ Response 200





# Group CITY

## ExampleCom Addresses Cities [//example.com/addresses/cities/]

### Get all cities [GET]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Addresses Cities 2b9d5940 2b15 11e8 85a5 9d1b727ad583 [//example.com/addresses/cities/2b9d5940-2b15-11e8-85a5-9d1b727ad583]

### Get one city [GET]

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Addresses Cities [//example.com/addresses/cities/{?parent_id}]

### Get all cities of province [GET]
+ Parameters
    + parent_id (string, required)

        + Sample: 2b85d9a0-2b15-11e8-85a5-9d1b727ad583

+ Request (application/json)
    + Headers

            Authorization:{{authorization}}




+ Response 200





# Group SEARCH

## ExampleCom Search Suggest [//example.com/search/suggest{?q}]

### Search Using Query [GET]
+ Parameters
    + q (string, required)

        + Sample: s

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200




## ExampleCom Search Suggest [//example.com/search/suggest{?popular}]

### Get Popular Searches [GET]
+ Parameters
    + popular (boolean, required)

        + Sample: true

+ Request
    + Headers

            Authorization:{{authorization}}




+ Response 200





# Data Structures

## Delete oneRequest (object)


### Properties
+ `name`: `modem-1` (string, required)
+ `purchase_date`: `2/13/2018 12:00:00 AM` (string, required)
+ `supplier`: `vodafone` (string, required)
+ `status`: `broken` (string, required)
+ `purchase_price`: `700.0000` (string, required)
+ `warehouse`: `sing-tel-ware` (string, required)
+ `currency_code`: `USD` (string, required)


## Add Attraction to WishlistRequest (object)


### Properties
+ `attractionUUID`: `642cf2e0-f2bf-5120-a496-6383be750b62` (string, required)


## Voucher ReadyRequest (object)


### Properties
+ `type`: `vouchers_ready` (string, required)
+ `timestamp`: `2017-11-26 10:43:14` (string, required)
+ `links`: `2017-11-26 10:43:14` (Links, required)
+ `item`: `2017-11-26 10:43:14` (Item, required)


## Links (object)


### Properties
+ `self`: `https://api.bemyguest.com.sg/v2/bookings/8a4970bf-b9dd-448b-8c24-59dadb5c3766` (string, required)


## Item (object)


### Properties
+ `uuid`: `8a4970bf-b9dd-448b-8c24-59dadb5c3766` (string, required)
+ `code`: `UVWXP81` (string, required)
+ `partnerReference` (string, required, nullable)
+ `status`: `approved` (string, required)
+ `productTypeTitle`: `Universal Studios Singapore E-ticket` (string, required)
+ `productTypeTitleTranslated`: `Universal Studios Singapore E-ticket` (string, required)
+ `productTypeUuid`: `efedb1fc-f150-5eaa-bf6e-fc202f6114bd` (string, required)
+ `currencyCode`: `SGD` (string, required)
+ `currencyUuid`: `cd15153e-dfd1-5039-8aa3-115bec58e86e` (string, required)
+ `totalAmount`: `113.5` (number, required)
+ `amountBreakdown`: `113.5` (array[AmountBreakdown], required)
+ `arrivalDate`: `2017-12-25` (string, required)
+ `createdAt`: `2017-11-06 14:31:59` (string, required)
+ `updatedAt`: `2017-12-12 16:16:36` (string, required)
+ `salutation`: `Mr.` (string, required)
+ `firstName`: `John` (string, required)
+ `lastName`: `Doe` (string, required)
+ `email`: `john@sample.com` (string, required)
+ `phone`: `+222333111` (string, required)
+ `adults`: `1` (number, required)
+ `children`: `1` (number, required)
+ `seniors`: `0` (number, required)
+ `options`: `[]` (array[string], required)
+ `completedAt` (string, required, nullable)
+ `cancellationRequestAt` (string, required, nullable)
+ `refundDate` (string, required, nullable)
+ `refundAmount` (string, required, nullable)
+ `refundTransaction` (string, required, nullable)


## AmountBreakdown (object)


### Properties
+ `name`: `adult` (string, required)
+ `quantity`: `1` (number, required)
+ `price`: `65` (number, required)


## Set maintenance statusRequest (object)


### Properties
+ `value`: `true` (boolean, required)


## ClaimersDelete coupons claimer relationship with userRequest (object)


### Properties
+ `userUUID`: `6d730960-1133-11e8-b815-ef31569eb8a0` (string, required)


## Add to Cart ModemRequest (object)


### Properties
+ `productable_id` (string, required)
+ `productable_type`: `product` (string, required)
+ `order_detail`: `product` (OrderDetail, required)


## OrderDetail (object)


### Properties
+ `qty`: `1` (number, required)


## Local Login  AdminRequest (object)


### Properties
+ `email`: `admin@passpod.id` (string, required)
+ `password`: `password` (string, required)


## Add Attraction to Current User WishlistRequest (object)


### Properties
+ `couponUUID`: `262c2580-1775-11e8-9284-07fb71fb3431` (string, required)


## Resend Activation mailRequest (object)


### Properties
+ `email`: `wisnugrohosatrio@gmail.com` (string, required)


## Update one ModemRequest (object)


### Properties
+ `title`: `Modem One` (string, required)
+ `description`: `Vodafone modem available to rent.` (string, required)
+ `price`: `100` (number, required)
+ `currency_code`: `USD` (string, required)
+ `image_file`: `image-data.jpg` (string, required)
+ `product_type`: `modem` (string, required)
+ `status`: `active` (string, required)
+ `details`: `active` (Details, required)


## Details (object)


### Properties
+ `country_id`: `10a34500-5b55-53f8-baae-6f7f038eaa56` (string, required)


## Eligible UsersDelete coupons eligibleusers relation with userRequest (object)


### Properties
+ `userUUID`: `6d730960-1133-11e8-b815-ef31569eb8a0` (string, required)


## ClaimersCreate coupons claimer relationship with userRequest (object)


### Properties
+ `userUUID`: `6d730960-1133-11e8-b815-ef31569eb8a0` (string, required)


## Social LoginRequest (object)


### Properties
+ `provider_type`: `facebook` (string, required)
+ `provider_id`: `10209485407847211` (string, required)
+ `provider_token`: `EAAQiGg8LuYMBAC4TDm4VeZC2iEP9qiCxDZBivg89baV8kFjvxhPwOoWHvVroZCz1XsiPGeS8o0DeKIgZBJnIB6aDH29XXebffuoZAD8NjRNEN34E7dfhaDtKZAS7Cq4N2fBtK8OJzuYuqruiw0QYOfqCA20a4dRBAZD` (string, required)
+ `notification_key`: `fhh33XfKLe4:APA91bEXCK09U4j2t33r7EE1-kMm0ryx4YR0bVsNguAePGruhsO5nCODvAiHYcVNunW-3UnJzvjhugFXDEvSQ1ECCiHnXFNLZ9xAyythGgboS0Lg9Xz7LJ8154WtvYUoS_kQ7zV7lxqE` (string, required)


## Create DestinationRequest (object)


### Properties
+ `name`: `Java` (string, required)
+ `image_file`: `Java` (ImageFile, required)
+ `experience_count`: `0` (number, required)
+ `priority`: `1` (number, required)


## ImageFile (object)


### Properties
+ `wide`: `singapore-wide.jpg` (string, required)
+ `narrow`: `singapore-narrow.jpg` (string, required)


## Update couponRequest (object)


### Properties
+ `id`: `262c2580-1775-11e8-9284-07fb71fb3431` (string, required)
+ `code`: `YEYEAH` (string, required)
+ `title`: `Discount akhir tahun lagi!` (string, required)
+ `status`: `unavailable` (string, required)
+ `image_file`: `sample-image.jpg` (string, required)
+ `max_usage`: `10` (string, required)
+ `max_usage_per_user`: `2` (string, required)
+ `platform`: `all` (string, required)
+ `first_order_only`: `false` (boolean, required)
+ `first_user_only`: `false` (boolean, required)
+ `product_type`: `all` (string, required)
+ `discount_type`: `PERCENTAGE_CUT` (string, required)
+ `discount_amount`: `0` (string, required)
+ `start_at`: `3/8/2018 9:57:32 AM` (string, required)
+ `end_at`: `4/8/2018 9:57:32 AM` (string, required)
+ `description`: `Something is happening! Take cover!` (string, required)
+ `min_amount`: `500000` (number, required)
+ `country_code` (string, required, nullable)


## Update oneRequest (object)


### Properties
+ `name`: `modem-1` (string, required)
+ `purchase_date`: `2/13/2018 12:00:00 AM` (string, required)
+ `supplier`: `vodafone` (string, required)
+ `status`: `broken` (string, required)
+ `purchase_price`: `700.0000` (string, required)
+ `warehouse`: `sing-tel-ware` (string, required)
+ `currency_code`: `USD` (string, required)


## Add to Cart AttractionRequest (object)


### Properties
+ `productable_id`: `d5a03ea2-e06e-5d01-84b7-94530b1059f7` (string, required)
+ `productable_type`: `attraction` (string, required)
+ `order_detail`: `attraction` (OrderDetail24, required)


## OrderDetail24 (object)


### Properties
+ `attraction_package_id`: `efedb1fc-f150-5eaa-bf6e-fc202f6114bd` (string, required)
+ `date`: `2018-03-16` (string, required)
+ `adults`: `1` (number, required)
+ `children`: `0` (number, required)
+ `seniors`: `0` (number, required)
+ `time_slot_id` (string, required, nullable)


## Update one markup pricesRequest (object)


### Properties
+ `attraction_id`: `6d730960-1133-11e8-b815-ef31569eb8a0` (string, required)
+ `markup_value`: `1200` (string, required)


## RegisterRequest (object)


### Properties
+ `first_name`: `Skyshi` (string, required)
+ `last_name`: `Tampomas` (string, required)
+ `email`: `developer@skyshi.com` (string, required)
+ `password`: `12345678` (string, required)


## Request Phone Number Ownership Verification Send OTPRequest (object)


### Properties
+ `phone_number`: `+628231231233` (string, required)


## Update UserRequest (object)


### Properties
+ `first_name`: `Satrio` (string, required)
+ `last_name`: `Wisnugroho` (string, required)
+ `country_code`: `ID` (string, required)
+ `language_code`: `ID` (string, required)
+ `currency_code`: `IDR` (string, required)
+ `old_password`: `password` (string, required)
+ `password`: `12345678` (string, required)
+ `profile_picture`: `profile_693e9af84d10c16df38c1e27e1dbb7_0.png` (string, required)


## Checkout for Current UserRequest (object)


### Properties
+ `salutation`: `Mr.` (string, required)
+ `first_name`: `Satrio` (string, required)
+ `last_name`: `Wisnugroho` (string, required)
+ `email`: `wisnugrohosatrio@gmail.com` (string, required)
+ `phone_number`: `+6282138844644` (string, required)


## Remove Attraction from Current User WishlistRequest (object)


### Properties
+ `couponUUID`: `262c2580-1775-11e8-9284-07fb71fb3431` (string, required)


## Create new markup pricesRequest (object)


### Properties
+ `attraction_id`: `6d730960-1133-11e8-b815-ef31569eb8a0` (string, required)
+ `markup_value`: `120` (string, required)


## Local Login  Normal UserRequest (object)


### Properties
+ `email`: `wisnugrohosatrio@gmail.com` (string, required)
+ `password`: `password` (string, required)


## Update single bannerRequest (object)


### Properties
+ `title`: `Banner Ones` (string, required)
+ `priority`: `3` (number, required)
+ `image_file`: `3` (ImageFile34, required)


## ImageFile34 (object)


### Properties
+ `mobile`: `9bd88ed0-2365-11e8-aedc-2d60910e9b56-mobile.jpg` (string, required)
+ `original`: `9bd88ed0-2365-11e8-aedc-2d60910e9b56-original.jpg` (string, required)


## Update DestinationRequest (object)


### Properties
+ `priority`: `100` (number, required)


## Register new bannerRequest (object)


### Properties
+ `title`: `Banner One` (string, required)
+ `priority`: `3` (number, required)
+ `image_file`: `3` (ImageFile34, required)


## Verify Phone Number ChangeRequest (object)


### Properties
+ `code`: `82233332593` (string, required)


## Add popular attractionRequest (object)


### Properties
+ `attraction_id`: `d5a03ea2-e06e-5d01-84b7-94530b1059f7` (string, required)
+ `modifier_type`: `origin` (string, required)
+ `modifier_value`: `id` (string, required)
+ `priority`: `1` (number, required)


## Reset PasswordRequest (object)


### Properties
+ `token`: `U2FsdGVkX1/KszvvNLReh6J89uW7WSC6qzjn5m7lINSnN8lwGeaa9yGL2VEi4HX+/jeb1zNtvjLRJvxt4twiXQ==` (string, required)
+ `new_password`: `12345678` (string, required)


## Create new couponRequest (object)


### Properties
+ `title`: `Diskon akhir tahun` (string, required)
+ `code`: `BANGBANG` (string, required)
+ `status`: `available` (string, required)
+ `max_usage`: `1` (string, required)
+ `max_usage_per_user`: `1` (string, required)
+ `image_file`: `sample-image.jpg` (string, required)
+ `discount_type`: `PRICE_CUT` (string, required)
+ `discount_amount`: `200000` (string, required)
+ `start_at`: `2/18/2018 12:00:00 AM` (string, required)
+ `end_at`: `2/21/2018 12:00:00 AM` (string, required)
+ `description` (string, required, nullable)
+ `min_amount`: `0` (number, required)


## Create new couponErrorResponse (object)


### Properties
+ `code`: `400` (number, required)
+ `status`: `false` (boolean, required)
+ `message`: `Bad Request` (string, required)
+ `meta`: `{}` (object, required)
+ `data`: `{}` (array[Datum], required)


## Datum (object)


### Properties
+ `title.presence` (TitlePresence, required)


## TitlePresence (object)


### Properties
+ `en`: `Title can't be blank` (string, required)
+ `id`: `Title can't be blank` (string, required)


## Update popular attractionRequest (object)


### Properties
+ `attraction_id`: `258c5832-1ac6-11e8-8572-100ba914aaac` (string, required)
+ `origin`: `eng` (string, required)
+ `priority`: `1` (number, required)


## Eligible UsersCreate coupons eligibleusers relation with userRequest (object)


### Properties
+ `userUUID`: `6d730960-1133-11e8-b815-ef31569eb8a0` (string, required)


## Forgot PasswordRequest (object)


### Properties
+ `email`: `wisnugrohosatrio@gmail.com` (string, required)


## Create new ModemRequest (object)


### Properties
+ `title`: `Sample Modem One` (string, required)
+ `description`: `Vodafone modem available to rent.` (string, required)
+ `price`: `100` (number, required)
+ `currency_code`: `USD` (string, required)
+ `image_file`: `image-data.jpg` (string, required)
+ `product_type`: `modem` (string, required)
+ `status`: `active` (string, required)
+ `details`: `active` (Details, required)


## Create newRequest (object)


### Properties
+ `name`: `modem-1` (string, required)
+ `purchase_date`: `2/13/2018 12:00:00 AM` (string, required)
+ `supplier`: `vodafone` (string, required)
+ `status`: `broken` (string, required)
+ `purchase_price`: `700.0000` (string, required)
+ `warehouse`: `sing-tel-ware` (string, required)
+ `currency_code`: `USD` (string, required)


## Verify Phone Number OwnershipRequest (object)


### Properties
+ `code`: `568124` (string, required)


## Local LoginRequest (object)


### Properties
+ `email`: `wisnugrohosatrio@gmail.com` (string, required)
+ `password`: `password` (string, required)
+ `notification_key`: `dT4k4zE5ae8:APA91bFkNI42O-UhYk9I27npk24Mt80ltiSEE_7msarN8NMbzGEAg52vMkl8v6Z0m2_bnkXZsL4hDrdjsVbye2RWc0u_xy_uqHfONM4zkyBtsqvub4lqY1QrjBsk99xUEdnejU8NAkv7` (string, required)


## Request Phone Number ChangeRequest (object)


### Properties
+ `phone_number`: `+6282233332593` (string, required)


## RegisterRequest54 (object)


### Properties
+ `first_name`: `Skyshi` (string, required)
+ `last_name`: `Tampomas` (string, required)
+ `email`: `developessr@skyshi.com` (string, required)
+ `password`: `12345678` (string, required)
+ `notification_key`: `dF_3FA64NAg:APA91bFkli43f9zA7JAOJt9rzRGIdzLUncUWkTlTP944us2z6_A4s1PbUlozj_lXfzeEg340LxNxbYKu1cCDVjPZIsk5jV8H8e4uyft6ElzZB-jTv4aLQu0jRxmPugZCqSLXFPBrNke-` (string, required)


## Booking Status ChangedRequest (object)


### Properties
+ `type`: `booking_status_changed` (string, required)
+ `timestamp`: `2017-11-26 10:43:14` (string, required)
+ `links`: `2017-11-26 10:43:14` (Links, required)
+ `item`: `2017-11-26 10:43:14` (Item, required)
