## Maintenance Status [/presets]

### Maintenance status [GET {{base_url}}/maintenance-status]

+ Response 200

        {
            "code": 200,
            "status": true,
            "message": "Success accessing maintenance status preset",
            "i18n": {},
            "data": {
                "maintenance_status": "false"
            },
            "meta": {}
        }


# Data Structures