## Presets [/presets]

### Get about preset [GET /presets/about{?language}]
+ Parameters
    + language (string, required)

        + Sample: id

+ Response 200

        {
            "code": 200,
            "status": true,
            "message": "Success accessing about presets",
            "i18n": {},
            "data": {
                "appName": "Passpod Application",
                "officialPage": "https://passpod.id/",
                "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
            },
            "meta": {}
        }

### Get currency code list preset [GET /presets/countries]

+ Response 200

        {
            "code": 200,
            "status": true,
            "message": "Success accessing country list presets",
            "i18n": {},
            "data": [
                {
                    "code": "AFG",
                    "country": "Afghanistan"
                },
                {
                    "code": "ALA",
                    "country": "Aland Islands"
                },
                {
                    "code": "ALB",
                    "country": "Albania"
                },
                {
                    "code": "DZA",
                    "country": "Algeria"
                },
                {
                    "code": "ASM",
                    "country": "American Samoa"
                },
                {
                    "code": "AND",
                    "country": "Andorra"
                },
                {
                    "code": "AGO",
                    "country": "Angola"
                },
                {
                    "code": "AIA",
                    "country": "Anguilla"
                },
                {
                    "code": "AQ",
                    "country": " "
                },
                {
                    "code": "ATG",
                    "country": "Antigua and Barbuda"
                },
                {
                    "code": "ARG",
                    "country": "Argentina"
                },
                {
                    "code": "ARM",
                    "country": "Armenia"
                },
                {
                    "code": "ABW",
                    "country": "Aruba"
                },
                {
                    "code": "AUS",
                    "country": "Australia"
                },
                {
                    "code": "AUT",
                    "country": "Austria"
                },
                {
                    "code": "AZE",
                    "country": "Azerbaijan"
                },
                {
                    "code": "BHS",
                    "country": "Bahamas"
                },
                {
                    "code": "BHR",
                    "country": "Bahrain"
                },
                {
                    "code": "BGD",
                    "country": "Bangladesh"
                },
                {
                    "code": "BRB",
                    "country": "Barbados"
                },
                {
                    "code": "BLR",
                    "country": "Belarus"
                },
                {
                    "code": "BEL",
                    "country": "Belgium"
                },
                {
                    "code": "BLZ",
                    "country": "Belize"
                },
                {
                    "code": "BEN",
                    "country": "Benin"
                },
                {
                    "code": "BMU",
                    "country": "Bermuda"
                },
                {
                    "code": "BTN",
                    "country": "Bhutan"
                },
                {
                    "code": "BOL",
                    "country": "Bolivia"
                },
                {
                    "code": "BIH",
                    "country": "Bosnia and Herzegovina"
                },
                {
                    "code": "BWA",
                    "country": "Botswana"
                },
                {
                    "code": "BVT",
                    "country": "Bouvet Island"
                },
                {
                    "code": "BRA",
                    "country": "Brazil"
                },
                {
                    "code": "VGB",
                    "country": "British Virgin Islands"
                },
                {
                    "code": "IOT",
                    "country": "British Indian Ocean Territory"
                },
                {
                    "code": "BRN",
                    "country": "Brunei Darussalam"
                },
                {
                    "code": "BGR",
                    "country": "Bulgaria"
                },
                {
                    "code": "BFA",
                    "country": "Burkina Faso"
                },
                {
                    "code": "BDI",
                    "country": "Burundi"
                },
                {
                    "code": "KHM",
                    "country": "Cambodia"
                },
                {
                    "code": "CMR",
                    "country": "Cameroon"
                },
                {
                    "code": "CAN",
                    "country": "Canada"
                },
                {
                    "code": "CPV",
                    "country": "Cape Verde"
                },
                {
                    "code": "CYM",
                    "country": "Cayman Islands"
                },
                {
                    "code": "CAF",
                    "country": "Central African Republic"
                },
                {
                    "code": "TCD",
                    "country": "Chad"
                },
                {
                    "code": "CHL",
                    "country": "Chile"
                },
                {
                    "code": "CHN",
                    "country": "China"
                },
                {
                    "code": "HKG",
                    "country": "Hong Kong, SAR China"
                },
                {
                    "code": "MAC",
                    "country": "Macao, SAR China"
                },
                {
                    "code": "CXR",
                    "country": "Christmas Island"
                },
                {
                    "code": "CCK",
                    "country": "Cocos (Keeling) Islands"
                },
                {
                    "code": "COL",
                    "country": "Colombia"
                },
                {
                    "code": "COM",
                    "country": "Comoros"
                },
                {
                    "code": "COG",
                    "country": "Congo (Brazzaville)"
                },
                {
                    "code": "COD",
                    "country": "Congo, (Kinshasa)"
                },
                {
                    "code": "COK",
                    "country": "Cook Islands"
                },
                {
                    "code": "CRI",
                    "country": "Costa Rica"
                },
                {
                    "code": "CIV",
                    "country": "Côte d'Ivoire"
                },
                {
                    "code": "HRV",
                    "country": "Croatia"
                },
                {
                    "code": "CUB",
                    "country": "Cuba"
                },
                {
                    "code": "CYP",
                    "country": "Cyprus"
                },
                {
                    "code": "CZE",
                    "country": "Czech Republic"
                },
                {
                    "code": "DNK",
                    "country": "Denmark"
                },
                {
                    "code": "DJI",
                    "country": "Djibouti"
                },
                {
                    "code": "DMA",
                    "country": "Dominica"
                },
                {
                    "code": "DOM",
                    "country": "Dominican Republic"
                },
                {
                    "code": "ECU",
                    "country": "Ecuador"
                },
                {
                    "code": "EGY",
                    "country": "Egypt"
                },
                {
                    "code": "SLV",
                    "country": "El Salvador"
                },
                {
                    "code": "GNQ",
                    "country": "Equatorial Guinea"
                },
                {
                    "code": "ERI",
                    "country": "Eritrea"
                },
                {
                    "code": "EST",
                    "country": "Estonia"
                },
                {
                    "code": "ETH",
                    "country": "Ethiopia"
                },
                {
                    "code": "FLK",
                    "country": "Falkland Islands (Malvinas)"
                },
                {
                    "code": "FRO",
                    "country": "Faroe Islands"
                },
                {
                    "code": "FJI",
                    "country": "Fiji"
                },
                {
                    "code": "FIN",
                    "country": "Finland"
                },
                {
                    "code": "FRA",
                    "country": "France"
                },
                {
                    "code": "GUF",
                    "country": "French Guiana"
                },
                {
                    "code": "PYF",
                    "country": "French Polynesia"
                },
                {
                    "code": "ATF",
                    "country": "French Southern Territories"
                },
                {
                    "code": "GAB",
                    "country": "Gabon"
                },
                {
                    "code": "GMB",
                    "country": "Gambia"
                },
                {
                    "code": "GEO",
                    "country": "Georgia"
                },
                {
                    "code": "DEU",
                    "country": "Germany"
                },
                {
                    "code": "GHA",
                    "country": "Ghana"
                },
                {
                    "code": "GIB",
                    "country": "Gibraltar"
                },
                {
                    "code": "GRC",
                    "country": "Greece"
                },
                {
                    "code": "GRL",
                    "country": "Greenland"
                },
                {
                    "code": "GRD",
                    "country": "Grenada"
                },
                {
                    "code": "GLP",
                    "country": "Guadeloupe"
                },
                {
                    "code": "GUM",
                    "country": "Guam"
                },
                {
                    "code": "GTM",
                    "country": "Guatemala"
                },
                {
                    "code": "GGY",
                    "country": "Guernsey"
                },
                {
                    "code": "GIN",
                    "country": "Guinea"
                },
                {
                    "code": "GNB",
                    "country": "Guinea-Bissau"
                },
                {
                    "code": "GUY",
                    "country": "Guyana"
                },
                {
                    "code": "HTI",
                    "country": "Haiti"
                },
                {
                    "code": "HMD",
                    "country": "Heard and Mcdonald Islands"
                },
                {
                    "code": "VAT",
                    "country": "Holy See (Vatican City State)"
                },
                {
                    "code": "HND",
                    "country": "Honduras"
                },
                {
                    "code": "HUN",
                    "country": "Hungary"
                },
                {
                    "code": "ISL",
                    "country": "Iceland"
                },
                {
                    "code": "IND",
                    "country": "India"
                },
                {
                    "code": "IDN",
                    "country": "Indonesia"
                },
                {
                    "code": "IRN",
                    "country": "Iran, Islamic Republic of"
                },
                {
                    "code": "IRQ",
                    "country": "Iraq"
                },
                {
                    "code": "IRL",
                    "country": "Ireland"
                },
                {
                    "code": "IMN",
                    "country": "Isle of Man"
                },
                {
                    "code": "ISR",
                    "country": "Israel"
                },
                {
                    "code": "ITA",
                    "country": "Italy"
                },
                {
                    "code": "JAM",
                    "country": "Jamaica"
                },
                {
                    "code": "JPN",
                    "country": "Japan"
                },
                {
                    "code": "JEY",
                    "country": "Jersey"
                },
                {
                    "code": "JOR",
                    "country": "Jordan"
                },
                {
                    "code": "KAZ",
                    "country": "Kazakhstan"
                },
                {
                    "code": "KEN",
                    "country": "Kenya"
                },
                {
                    "code": "KIR",
                    "country": "Kiribati"
                },
                {
                    "code": "PRK",
                    "country": "Korea (North)"
                },
                {
                    "code": "KOR",
                    "country": "Korea (South)"
                },
                {
                    "code": "KWT",
                    "country": "Kuwait"
                },
                {
                    "code": "KGZ",
                    "country": "Kyrgyzstan"
                },
                {
                    "code": "LAO",
                    "country": "Lao PDR"
                },
                {
                    "code": "LVA",
                    "country": "Latvia"
                },
                {
                    "code": "LBN",
                    "country": "Lebanon"
                },
                {
                    "code": "LSO",
                    "country": "Lesotho"
                },
                {
                    "code": "LBR",
                    "country": "Liberia"
                },
                {
                    "code": "LBY",
                    "country": "Libya"
                },
                {
                    "code": "LIE",
                    "country": "Liechtenstein"
                },
                {
                    "code": "LTU",
                    "country": "Lithuania"
                },
                {
                    "code": "LUX",
                    "country": "Luxembourg"
                },
                {
                    "code": "MKD",
                    "country": "Macedonia, Republic of"
                },
                {
                    "code": "MDG",
                    "country": "Madagascar"
                },
                {
                    "code": "MWI",
                    "country": "Malawi"
                },
                {
                    "code": "MYS",
                    "country": "Malaysia"
                },
                {
                    "code": "MDV",
                    "country": "Maldives"
                },
                {
                    "code": "MLI",
                    "country": "Mali"
                },
                {
                    "code": "MLT",
                    "country": "Malta"
                },
                {
                    "code": "MHL",
                    "country": "Marshall Islands"
                },
                {
                    "code": "MTQ",
                    "country": "Martinique"
                },
                {
                    "code": "MRT",
                    "country": "Mauritania"
                },
                {
                    "code": "MUS",
                    "country": "Mauritius"
                },
                {
                    "code": "MYT",
                    "country": "Mayotte"
                },
                {
                    "code": "MEX",
                    "country": "Mexico"
                },
                {
                    "code": "FSM",
                    "country": "Micronesia, Federated States of"
                },
                {
                    "code": "MDA",
                    "country": "Moldova"
                },
                {
                    "code": "MCO",
                    "country": "Monaco"
                },
                {
                    "code": "MNG",
                    "country": "Mongolia"
                },
                {
                    "code": "MNE",
                    "country": "Montenegro"
                },
                {
                    "code": "MSR",
                    "country": "Montserrat"
                },
                {
                    "code": "MAR",
                    "country": "Morocco"
                },
                {
                    "code": "MOZ",
                    "country": "Mozambique"
                },
                {
                    "code": "MMR",
                    "country": "Myanmar"
                },
                {
                    "code": "NAM",
                    "country": "Namibia"
                },
                {
                    "code": "NRU",
                    "country": "Nauru"
                },
                {
                    "code": "NPL",
                    "country": "Nepal"
                },
                {
                    "code": "NLD",
                    "country": "Netherlands"
                },
                {
                    "code": "ANT",
                    "country": "Netherlands Antilles"
                },
                {
                    "code": "NCL",
                    "country": "New Caledonia"
                },
                {
                    "code": "NZL",
                    "country": "New Zealand"
                },
                {
                    "code": "NIC",
                    "country": "Nicaragua"
                },
                {
                    "code": "NER",
                    "country": "Niger"
                },
                {
                    "code": "NGA",
                    "country": "Nigeria"
                },
                {
                    "code": "NIU",
                    "country": "Niue"
                },
                {
                    "code": "NFK",
                    "country": "Norfolk Island"
                },
                {
                    "code": "MNP",
                    "country": "Northern Mariana Islands"
                },
                {
                    "code": "NOR",
                    "country": "Norway"
                },
                {
                    "code": "OMN",
                    "country": "Oman"
                },
                {
                    "code": "PAK",
                    "country": "Pakistan"
                },
                {
                    "code": "PLW",
                    "country": "Palau"
                },
                {
                    "code": "PSE",
                    "country": "Palestinian Territory"
                },
                {
                    "code": "PAN",
                    "country": "Panama"
                },
                {
                    "code": "PNG",
                    "country": "Papua New Guinea"
                },
                {
                    "code": "PRY",
                    "country": "Paraguay"
                },
                {
                    "code": "PER",
                    "country": "Peru"
                },
                {
                    "code": "PHL",
                    "country": "Philippines"
                },
                {
                    "code": "PCN",
                    "country": "Pitcairn"
                },
                {
                    "code": "POL",
                    "country": "Poland"
                },
                {
                    "code": "PRT",
                    "country": "Portugal"
                },
                {
                    "code": "PRI",
                    "country": "Puerto Rico"
                },
                {
                    "code": "QAT",
                    "country": "Qatar"
                },
                {
                    "code": "REU",
                    "country": "Réunion"
                },
                {
                    "code": "ROU",
                    "country": "Romania"
                },
                {
                    "code": "RUS",
                    "country": "Russian Federation"
                },
                {
                    "code": "RWA",
                    "country": "Rwanda"
                },
                {
                    "code": "BLM",
                    "country": "Saint-Barthélemy"
                },
                {
                    "code": "SHN",
                    "country": "Saint Helena"
                },
                {
                    "code": "KNA",
                    "country": "Saint Kitts and Nevis"
                },
                {
                    "code": "LCA",
                    "country": "Saint Lucia"
                },
                {
                    "code": "MAF",
                    "country": "Saint-Martin (French part)"
                },
                {
                    "code": "SPM",
                    "country": "Saint Pierre and Miquelon"
                },
                {
                    "code": "VCT",
                    "country": "Saint Vincent and Grenadines"
                },
                {
                    "code": "WSM",
                    "country": "Samoa"
                },
                {
                    "code": "SMR",
                    "country": "San Marino"
                },
                {
                    "code": "STP",
                    "country": "Sao Tome and Principe"
                },
                {
                    "code": "SAU",
                    "country": "Saudi Arabia"
                },
                {
                    "code": "SEN",
                    "country": "Senegal"
                },
                {
                    "code": "SRB",
                    "country": "Serbia"
                },
                {
                    "code": "SYC",
                    "country": "Seychelles"
                },
                {
                    "code": "SLE",
                    "country": "Sierra Leone"
                },
                {
                    "code": "SGP",
                    "country": "Singapore"
                },
                {
                    "code": "SVK",
                    "country": "Slovakia"
                },
                {
                    "code": "SVN",
                    "country": "Slovenia"
                },
                {
                    "code": "SLB",
                    "country": "Solomon Islands"
                },
                {
                    "code": "SOM",
                    "country": "Somalia"
                },
                {
                    "code": "ZAF",
                    "country": "South Africa"
                },
                {
                    "code": "SGS",
                    "country": "South Georgia and the South Sandwich Islands"
                },
                {
                    "code": "SSD",
                    "country": "South Sudan"
                },
                {
                    "code": "ESP",
                    "country": "Spain"
                },
                {
                    "code": "LKA",
                    "country": "Sri Lanka"
                },
                {
                    "code": "SDN",
                    "country": "Sudan"
                },
                {
                    "code": "SUR",
                    "country": "Suriname"
                },
                {
                    "code": "SJM",
                    "country": "Svalbard and Jan Mayen Islands"
                },
                {
                    "code": "SWZ",
                    "country": "Swaziland"
                },
                {
                    "code": "SWE",
                    "country": "Sweden"
                },
                {
                    "code": "CHE",
                    "country": "Switzerland"
                },
                {
                    "code": "SYR",
                    "country": "Syrian Arab Republic (Syria)"
                },
                {
                    "code": "TWN",
                    "country": "Taiwan, Republic of China"
                },
                {
                    "code": "TJK",
                    "country": "Tajikistan"
                },
                {
                    "code": "TZA",
                    "country": "Tanzania, United Republic of"
                },
                {
                    "code": "THA",
                    "country": "Thailand"
                },
                {
                    "code": "TLS",
                    "country": "Timor-Leste"
                },
                {
                    "code": "TGO",
                    "country": "Togo"
                },
                {
                    "code": "TKL",
                    "country": "Tokelau"
                },
                {
                    "code": "TON",
                    "country": "Tonga"
                },
                {
                    "code": "TTO",
                    "country": "Trinidad and Tobago"
                },
                {
                    "code": "TUN",
                    "country": "Tunisia"
                },
                {
                    "code": "TUR",
                    "country": "Turkey"
                },
                {
                    "code": "TKM",
                    "country": "Turkmenistan"
                },
                {
                    "code": "TCA",
                    "country": "Turks and Caicos Islands"
                },
                {
                    "code": "TUV",
                    "country": "Tuvalu"
                },
                {
                    "code": "UGA",
                    "country": "Uganda"
                },
                {
                    "code": "UKR",
                    "country": "Ukraine"
                },
                {
                    "code": "ARE",
                    "country": "United Arab Emirates"
                },
                {
                    "code": "GBR",
                    "country": "United Kingdom"
                },
                {
                    "code": "USA",
                    "country": "United States of America"
                },
                {
                    "code": "UMI",
                    "country": "US Minor Outlying Islands"
                },
                {
                    "code": "URY",
                    "country": "Uruguay"
                },
                {
                    "code": "UZB",
                    "country": "Uzbekistan"
                },
                {
                    "code": "VUT",
                    "country": "Vanuatu"
                },
                {
                    "code": "VEN",
                    "country": "Venezuela (Bolivarian Republic)"
                },
                {
                    "code": "VNM",
                    "country": "Viet Nam"
                },
                {
                    "code": "VIR",
                    "country": "Virgin Islands, US"
                },
                {
                    "code": "WLF",
                    "country": "Wallis and Futuna Islands"
                },
                {
                    "code": "ESH",
                    "country": "Western Sahara"
                },
                {
                    "code": "YEM",
                    "country": "Yemen"
                },
                {
                    "code": "ZMB",
                    "country": "Zambia"
                },
                {
                    "code": "ZWE",
                    "country": "Zimbabwe"
                }
            ],
            "meta": {}
        }

### Get country list preset [GET /presets/currencies]
+ Response 200

        {
            "code": 200,
            "status": true,
            "message": "Success accessing currency list presets",
            "i18n": {},
            "data": [
                {
                    "code": "IDR",
                    "name": "Rupiah",
                    "country": "Indonesia",
                    "support": true
                },
                {
                    "code": "SGD",
                    "name": "Singapore Dollar",
                    "country": "Singapore",
                    "support": true
                }
            ],
            "meta": {}
        }

### Get language list preset [GET /presets/languages]
+ Response 200

        {
            "code": 200,
            "status": true,
            "message": "Success accessing language list presets",
            "i18n": {},
            "data": [
                {
                    "code": "ind",
                    "name": "Indonesian",
                    "support": true
                },
                {
                    "code": "eng",
                    "name": "English",
                    "support": true
                }
            ],
            "meta": {}
        }


# Data Structures