## Search [/search]

### Search by query [GET /suggest/{?q}]
+ Parameters
    + q (string, required)

        + Sample: s

+ Request (application/json)
    + Headers

            Authorization: {{authorization}}

+ Response 200

        {
            "code": 200,
            "status": true,
            "message": "Suggestion",
            "i18n": {},
            "data": [
                {
                    "id": "5a5682b8-c8d6-5f15-97ef-de4c66ea5701",
                    "text": "Seoul",
                    "type": "destination",
                    "city": null,
                    "popularity": 5
                },
                {
                    "id": "5a5682b8-c8d6-5f15-97ef-de4c66ea5695",
                    "text": "Singapore",
                    "type": "destination",
                    "city": null,
                    "popularity": 19
                },
                {
                    "id": "ec1897a3-86fb-525c-914b-bfe39a4d5396",
                    "text": "Tiket Masuk Jurong Bird Park dengan Trem (dengan pilihan makan siang)",
                    "type": "attraction",
                    "city": "Singapore",
                    "popularity": 0
                },
                {
                    "id": "e8f0b93c-ee5d-54b7-8813-8004c26c658c",
                    "text": "Night Safari: Tanggal buka dan tiket masuk dengan Trem Berpanduan Bahasa Inggris",
                    "type": "attraction",
                    "city": "Singapore",
                    "popularity": 0
                },
                {
                    "id": "dd15d4fc-4ca2-4ff9-a663-0c45a7de47a9",
                    "text": "Marina Bay Sands: Dek Observasi Sands SkyPark",
                    "type": "attraction",
                    "city": "Singapore",
                    "popularity": 0
                },
                {
                    "id": "dadee289-0f4f-5fff-8145-8b562a35cd70",
                    "text": "Skyline Luge Sentosa",
                    "type": "attraction",
                    "city": "Sentosa",
                    "popularity": 0
                },
                {
                    "id": "d5a03ea2-e06e-5d01-84b7-94530b1059f7",
                    "text": "E-tiket Universal Studio Singapore ",
                    "type": "attraction",
                    "city": "Sentosa",
                    "popularity": 0
                },
                {
                    "id": "d4398f47-9fc0-5f38-ba2d-d04a5fe8327e",
                    "text": "Singapore Zoo : Tiket masuk dengan tiket trem (dengan pilihan sarapan)",
                    "type": "attraction",
                    "city": "Singapore",
                    "popularity": 0
                },
                {
                    "id": "d221b76f-fb0a-435c-917f-00db8dd8d6e0",
                    "text": "Tiket Masuk ArtScience Museum™",
                    "type": "attraction",
                    "city": "Singapore",
                    "popularity": 0
                },
                {
                    "id": "ac1ae895-1992-5666-b3c3-cec52e7c64c4",
                    "text": "Tiger Sky Tower Singapura",
                    "type": "attraction",
                    "city": "Sentosa",
                    "popularity": 0
                }
            ],
            "meta": {}
        }

### Get Popular Searches [GET /suggest/{?popular}]
+ Parameters
    + popular (boolean, required)

        + Sample: true

+ Request (application/json)
    + Headers

            Authorization: {{authorization}}

+ Response 200

            {
                "code": 200,
                "status": true,
                "message": "Suggestion",
                "i18n": {},
                "data": [
                    {
                        "id": "5a5682b8-c8d6-5f15-97ef-de4c66ea5695",
                        "text": "Singapore",
                        "type": "destination",
                        "city": null,
                        "popularity": 19
                    },
                    {
                        "id": "5a5682b8-c8d6-5f15-97ef-de4c66ea5701",
                        "text": "Seoul",
                        "type": "destination",
                        "city": null,
                        "popularity": 5
                    },
                    {
                        "id": "5a5682b8-c8d6-5f15-97ef-de4c66ea5698",
                        "text": "Kuala Lumpur",
                        "type": "destination",
                        "city": null,
                        "popularity": 4
                    },
                    {
                        "id": "5a5682b8-c8d6-5f15-97ef-de4c66ea5702",
                        "text": "Phuket",
                        "type": "destination",
                        "city": null,
                        "popularity": 3
                    },
                    {
                        "id": "5a5682b8-c8d6-5f15-97ef-de4c66ea5699",
                        "text": "Bangkok",
                        "type": "destination",
                        "city": null,
                        "popularity": 3
                    },
                    {
                        "id": "5a5682b8-c8d6-5f15-97ef-de4c66ea5700",
                        "text": "Osaka",
                        "type": "destination",
                        "city": null,
                        "popularity": 1
                    },
                    {
                        "id": "5a5682b8-c8d6-5f15-97ef-de4c66ea5697",
                        "text": "Tokyo",
                        "type": "destination",
                        "city": null,
                        "popularity": 1
                    },
                    {
                        "id": "5a5682b8-c8d6-5f15-97ef-de4c66ea5696",
                        "text": "Hong Kong",
                        "type": "destination",
                        "city": null,
                        "popularity": 1
                    },
                    {
                        "id": "ec1897a3-86fb-525c-914b-bfe39a4d5396",
                        "text": "Tiket Masuk Jurong Bird Park dengan Trem (dengan pilihan makan siang)",
                        "type": "attraction",
                        "city": "Singapore",
                        "popularity": 0
                    },
                    {
                        "id": "ec1897a3-86fb-525c-914b-bfe39a4d5396",
                        "text": "Jurong Bird Park: Admission with Tram Ride (with Lunch Option)",
                        "type": "attraction",
                        "city": "Singapore",
                        "popularity": 0
                    }
                ],
                "meta": {}
            }